### ISSUE TITLE
E_NOTICE Undefined offset: 0

### ISSUE THREAD

**Issue by HRoger** [unfulvio/wp-php-console#14]
Hi there, 

I'm getting the following notice:

E_NOTICE Undefined offset: 0

/wp-includes/capabilities.php 127.
 
Thanks

**Comment by unfulvio** [comment]
That error is related to WordPress, not WP PHP Console. The plugin lets you discover errors, in WordPress or your theme/plugins. You need to understand why it is produced, you might want to look in the console stack trace for clues.
