### ISSUE TITLE
How to avoid "Fatal error: Uncaught Error: Class 'PC' not found"

### ISSUE THREAD

**Issue by rafaelsaback** [unfulvio/wp-php-console#18]
Hi Fulvio,

First I'd like to thank you for creating such a useful plugin for PHP developers in WP. I've read in your plugin page the reason why I'm getting the error `Fatal error: Uncaught Error: Class 'PC' not found`, but I could not understand 100% how to solve it.

When you write that we can use the following code bellow, where exactly should I place it in?
```php
// PHP Console autoload
require_once dirname( __FILE__ ) . '/wp-php-console/vendor/autoload.php';

// make PC class available in global PHP scope
if ( ! class_exists( 'PC', false ) ) PhpConsole\Helper::register();
```

**Comment by unfulvio** [comment]
Hey there, 

perhaps this might be helpful to you:

https://wordpress.org/support/topic/working-with-plugin-development/

thanks for checking in
